# Generated by Django 5.2.17 on 2026-08-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityGrade',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_name', models.CharField(db_column='ActivityName', max_length=200)),
                ('max_score', models.DecimalField(db_column='MaxScore', decimal_places=2, max_digits=6)),
                ('student_score', models.DecimalField(db_column='StudentScore', decimal_places=2, max_digits=6)),
                ('teacher_note', models.TextField(blank=True, db_column='TeacherNote', default='')),
                ('visible_to', models.CharField(choices=[('student', 'الطالب فقط'), ('parent', 'الأهل فقط'), ('student_parent', 'الطالب والأهل')], db_column='VisibleTo', default='student_parent', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
            ],
            options={
                'db_table': 'ActivityGrade',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Conversation',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GradeOverride',
            fields=[
                ('override_id', models.AutoField(primary_key=True, serialize=False)),
                ('adjusted_score', models.DecimalField(db_column='AdjustedScore', decimal_places=2, max_digits=6)),
                ('reason', models.TextField(db_column='Reason')),
                ('teacher_note', models.TextField(blank=True, db_column='TeacherNote', default='')),
                ('visible_to', models.CharField(choices=[('student', 'الطالب فقط'), ('parent', 'الأهل فقط'), ('student_parent', 'الطالب والأهل')], db_column='VisibleTo', default='student_parent', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
            ],
            options={
                'db_table': 'GradeOverride',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=2000)),
                ('is_read', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Message',
                'ordering': ['sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notif_id', models.AutoField(primary_key=True, serialize=False)),
                ('notif_type', models.CharField(choices=[('lesson_view', 'طالب شاهد الدرس'), ('test_attempt', 'طالب حل الاختبار'), ('lesson_publish', 'درس جديد منشور'), ('test_publish', 'اختبار جديد منشور'), ('schedule_update', 'تحديث جدول المهام'), ('grade_update', 'تحديث درجة'), ('test_modified', 'تعديل في الاختبار'), ('parent_grade', 'رصد درجة الطالب'), ('parent_note', 'ملاحظة من المعلم'), ('parent_attention', 'تنبيه تشتت الانتباه'), ('parent_lesson', 'درس جديد للطالب'), ('parent_test', 'اختبار جديد للطالب'), ('parent_result', 'نتيجة اختبار الطالب')], db_column='NotifType', max_length=20)),
                ('title', models.CharField(db_column='Title', max_length=200)),
                ('body', models.TextField(db_column='Body')),
                ('is_read', models.BooleanField(db_column='IsRead', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
            ],
            options={
                'db_table': 'Notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('lesson', 'حصة'), ('exam', 'اختبار')], db_column='EntryType', max_length=10)),
                ('entry_date', models.DateField(db_column='EntryDate')),
                ('start_time', models.TimeField(db_column='StartTime')),
                ('end_time', models.TimeField(db_column='EndTime')),
                ('notes', models.CharField(blank=True, db_column='Notes', default='', max_length=300)),
                ('online_link', models.URLField(blank=True, db_column='OnlineLink', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
            ],
            options={
                'db_table': 'ScheduleEntry',
                'ordering': ['entry_date', 'start_time'],
            },
        ),
    ]
