# Generated by Django 5.2.17 on 2026-08-18 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activitygrade',
            name='student',
            field=models.ForeignKey(db_column='StudentID', on_delete=django.db.models.deletion.CASCADE, related_name='activity_grades', to='learning.student'),
        ),
        migrations.AddField(
            model_name='activitygrade',
            name='subject',
            field=models.ForeignKey(db_column='SubjectID', on_delete=django.db.models.deletion.CASCADE, related_name='activity_grades', to='learning.subject'),
        ),
        migrations.AddField(
            model_name='activitygrade',
            name='teacher',
            field=models.ForeignKey(db_column='TeacherID', on_delete=django.db.models.deletion.CASCADE, related_name='activity_grades', to='learning.teacher'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='participant_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_p1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='participant_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_p2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gradeoverride',
            name='attempt',
            field=models.OneToOneField(db_column='AttemptID', on_delete=django.db.models.deletion.CASCADE, related_name='grade_override', to='learning.testattempt'),
        ),
        migrations.AddField(
            model_name='gradeoverride',
            name='teacher',
            field=models.ForeignKey(db_column='TeacherID', on_delete=django.db.models.deletion.CASCADE, related_name='grade_overrides', to='learning.teacher'),
        ),
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='accounts.conversation'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='lesson',
            field=models.ForeignKey(blank=True, db_column='LessonID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='learning.lessoncontent'),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(db_column='RecipientID', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='test',
            field=models.ForeignKey(blank=True, db_column='TestID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='learning.test'),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='class_obj',
            field=models.ForeignKey(db_column='ClassID', on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='learning.class'),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='subject',
            field=models.ForeignKey(db_column='SubjectID', on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='learning.subject'),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='teacher',
            field=models.ForeignKey(db_column='TeacherID', on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='learning.teacher'),
        ),
        migrations.AddIndex(
            model_name='activitygrade',
            index=models.Index(fields=['teacher', 'student', '-created_at'], name='idx_ag_teacher_student'),
        ),
        migrations.AddIndex(
            model_name='activitygrade',
            index=models.Index(fields=['subject', '-created_at'], name='idx_ag_subject_date'),
        ),
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('participant_1', 'participant_2')},
        ),
        migrations.AddIndex(
            model_name='gradeoverride',
            index=models.Index(fields=['teacher', '-created_at'], name='idx_go_teacher_date'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', '-created_at'], name='idx_notif_recipient_date'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='idx_notif_read'),
        ),
        migrations.AddIndex(
            model_name='scheduleentry',
            index=models.Index(fields=['class_obj', 'entry_date'], name='idx_schedule_class_date'),
        ),
        migrations.AddIndex(
            model_name='scheduleentry',
            index=models.Index(fields=['teacher', 'entry_date'], name='idx_schedule_teacher_date'),
        ),
    ]
