# Generated by Django 5.2.17 on 2026-08-18 13:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import learning.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiAgent',
            fields=[
                ('agentid', models.AutoField(db_column='AgentID', primary_key=True, serialize=False)),
                ('agentname', models.CharField(db_column='AgentName', max_length=50)),
                ('agenttype', models.CharField(db_column='AgentType', default='Gemini', max_length=50)),
                ('api_key', models.TextField(blank=True, db_column='API_Key', null=True)),
                ('version', models.CharField(db_column='Version', default='1.5-flash', max_length=50)),
                ('systeminstruction', models.TextField(db_column='SystemInstruction')),
                ('isactive', models.BooleanField(db_column='IsActive', default=True)),
            ],
            options={
                'db_table': 'AI_Agent',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('classid', models.AutoField(db_column='ClassID', primary_key=True, serialize=False)),
                ('classname', models.CharField(db_column='ClassName', max_length=50)),
            ],
            options={
                'db_table': 'Class',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Learningsession',
            fields=[
                ('sessionid', models.AutoField(db_column='SessionID', primary_key=True, serialize=False)),
                ('starttime', models.DateTimeField(auto_now_add=True, db_column='StartTime')),
                ('endtime', models.DateTimeField(blank=True, db_column='EndTime', null=True)),
                ('sessionstatus', models.CharField(db_column='SessionStatus', default='Active', max_length=20)),
                ('duration', models.DurationField(blank=True, db_column='Duration', null=True)),
                ('avgfocusscore', models.DecimalField(blank=True, db_column='AvgFocusScore', decimal_places=2, max_digits=5, null=True)),
                ('is_watched', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'LearningSession',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('userid', models.AutoField(db_column='UserID', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='Username', max_length=50, unique=True)),
                ('fullname', models.CharField(db_column='FullName', max_length=100)),
                ('email', models.EmailField(db_column='Email', max_length=100)),
                ('userrole', models.CharField(blank=True, choices=[('', 'نوع المستخدم'), ('Admin', 'مشرف تقني'), ('SysAdmin', 'مشرف إداري'), ('Student', 'طالب'), ('Teacher', 'معلم'), ('Parent', 'ولي أمر')], db_column='UserRole', max_length=50, null=True)),
                ('identitynumber', models.BigIntegerField(blank=True, db_column='IdentityNumber', null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('email_verification_code', models.CharField(blank=True, db_column='EmailVerificationCode', help_text='رمز التحقق من الإيميل (8 خانات)', max_length=8, null=True)),
                ('email_verification_sent_at', models.DateTimeField(blank=True, db_column='EmailVerificationSentAt', help_text='وقت إرسال رمز التحقق', null=True)),
                ('is_email_verified', models.BooleanField(db_column='IsEmailVerified', default=False, help_text='هل تم التحقق من الإيميل')),
                ('avatar', models.ImageField(blank=True, help_text='صورة شخصية (JPG/PNG/WebP — بحد أقصى 2MB)', null=True, upload_to=learning.models._avatar_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('bio', models.CharField(blank=True, default='', help_text='نبذة مختصرة عن المستخدم', max_length=300)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'User',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Attentionlog',
            fields=[
                ('logid', models.AutoField(db_column='LogID', primary_key=True, serialize=False)),
                ('logtime', models.DateTimeField(auto_now_add=True, db_column='LogTime')),
                ('focuspercentage', models.DecimalField(db_column='FocusPercentage', decimal_places=2, max_digits=5)),
                ('isdistracted', models.BooleanField(db_column='IsDistracted')),
                ('actiontaken', models.CharField(blank=True, db_column='ActionTaken', max_length=100, null=True)),
                ('sessionid', models.ForeignKey(db_column='SessionID', on_delete=django.db.models.deletion.CASCADE, to='learning.learningsession')),
            ],
            options={
                'db_table': 'AttentionLog',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AiInteraction',
            fields=[
                ('interactionid', models.AutoField(db_column='InteractionID', primary_key=True, serialize=False)),
                ('childquery', models.TextField(db_column='ChildQuery')),
                ('ai_response', models.TextField(db_column='AI_Response')),
                ('interactiontime', models.DateTimeField(auto_now_add=True, db_column='InteractionTime')),
                ('sessionid', models.ForeignKey(db_column='SessionID', on_delete=django.db.models.deletion.CASCADE, to='learning.learningsession')),
            ],
            options={
                'db_table': 'AI_Interaction',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lessoncontent',
            fields=[
                ('lessonid', models.AutoField(db_column='LessonID', primary_key=True, serialize=False)),
                ('lessontitle', models.CharField(db_column='LessonTitle', default='عنوان الدرس الجديد', max_length=200)),
                ('originaltext', models.TextField(db_column='OriginalText')),
                ('ai_visualpath', models.JSONField(blank=True, db_column='AI_VisualPath', default=list, null=True)),
                ('ai_audiopath', models.TextField(blank=True, db_column='AI_AudioPath', null=True)),
                ('ai_generatedtext', models.TextField(blank=True, db_column='AI_GeneratedText', null=True)),
                ('ai_videopath', models.TextField(blank=True, db_column='AI_VideoPath', null=True)),
                ('video_file', models.FileField(blank=True, help_text='فيديو تعليمي مرفوع يدوياً (MP4/WebM/MOV/AVI — بحد أقصى 500MB)', null=True, upload_to='lesson_videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'mov', 'avi'])])),
                ('video_title', models.CharField(blank=True, help_text='عنوان الفيديو التعليمي', max_length=200, null=True)),
                ('video_published', models.BooleanField(db_column='video_published', default=False)),
                ('complexitylevel', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], db_column='ComplexityLevel', default='Easy', max_length=10)),
                ('createdat', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Published', 'Published')], db_column='Status', default='Pending', max_length=10)),
                ('simplified_content', models.TextField(blank=True, null=True, verbose_name='المحتوى المبسط')),
                ('difficulty_level', models.CharField(blank=True, choices=[('simple', 'بسيط'), ('medium', 'متوسط'), ('advanced', 'عميق')], db_column='DifficultyLevel', default='simple', max_length=20)),
                ('learning_style', models.CharField(blank=True, db_column='LearningStyle', default='storytelling', max_length=30)),
                ('target_age_group', models.IntegerField(blank=True, db_column='TargetAgeGroup', null=True)),
                ('para_img_mapping', models.JSONField(blank=True, db_column='ParaImgMapping', default=dict)),
                ('content_updated_at', models.DateTimeField(blank=True, db_column='ContentUpdatedAt', null=True)),
                ('agentid', models.ForeignKey(blank=True, db_column='AgentID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.aiagent')),
            ],
            options={
                'db_table': 'LessonContent',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='learningsession',
            name='lessonid',
            field=models.ForeignKey(db_column='LessonID', on_delete=django.db.models.deletion.CASCADE, to='learning.lessoncontent'),
        ),
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('checkpointid', models.AutoField(db_column='CheckpointID', primary_key=True, serialize=False)),
                ('checkpoint_type', models.CharField(choices=[('mandatory', 'إجباري - دوري'), ('adaptive', 'تكيفي - عند انخفاض الانخراط')], db_column='CheckpointType', default='mandatory', help_text='نوع نقطة التحقق: إجباري (دوري) أو تكيفي (عند انخفاض الانخراط)', max_length=20)),
                ('display_type', models.CharField(choices=[('scheduled', 'مجدول - يظهر في الوقت المحدد فقط'), ('distraction', 'عند التشتت - يظهر فقط عند رصد التشتت'), ('both', 'كلاهما - يظهر في الوقت المحدد وعند التشتت')], db_column='DisplayType', default='scheduled', help_text='نوع العرض: مجدول (في الوقت المحدد فقط)، عند التشتت (فقط عند رصد التشتت)، أو كلاهما', max_length=20)),
                ('content_type', models.CharField(choices=[('text', 'نص'), ('audio', 'صوت'), ('video', 'فيديو')], db_column='ContentType', default='text', help_text='نوع المحتوى المرتبط بنقطة التحقق', max_length=10)),
                ('paragraph_index', models.IntegerField(blank=True, db_column='ParagraphIndex', help_text='رقم الفقرة (يبدأ من 0) - للنص فقط', null=True)),
                ('video_timestamp', models.FloatField(blank=True, db_column='VideoTimestamp', help_text='الوقت بالثواني في الفيديو - للفيديو فقط', null=True)),
                ('question', models.CharField(db_column='Question', help_text='سؤال قصير', max_length=500)),
                ('option_a', models.CharField(db_column='OptionA', help_text='الخيار الأول', max_length=300)),
                ('option_b', models.CharField(db_column='OptionB', help_text='الخيار الثاني', max_length=300)),
                ('option_c', models.CharField(blank=True, db_column='OptionC', help_text='الخيار الثالث (اختياري)', max_length=300, null=True)),
                ('option_d', models.CharField(blank=True, db_column='OptionD', help_text='الخيار الرابع (اختياري)', max_length=300, null=True)),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], db_column='CorrectAnswer', help_text='الإجابة الصحيحة (للمعلم فقط)', max_length=10)),
                ('mandatory_frequency', models.IntegerField(db_column='MandatoryFrequency', default=20, help_text='نسبة الأسئلة الإجبارية (مثلاً: 20 تعني سؤال إجباري كل 20% من المحتوى)')),
                ('engagement_threshold', models.FloatField(db_column='EngagementThreshold', default=0.5, help_text='عتبة الانخراط (0-1) لإظهار السؤال التكيفي')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
                ('lessonid', models.ForeignKey(db_column='LessonID', on_delete=django.db.models.deletion.CASCADE, to='learning.lessoncontent')),
            ],
            options={
                'db_table': 'Checkpoint',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentid', models.AutoField(db_column='StudentID', primary_key=True, serialize=False)),
                ('age', models.IntegerField(db_column='Age')),
                ('currentfocuslevel', models.FloatField(blank=True, db_column='CurrentFocusLevel', null=True)),
                ('chat_api_key', models.CharField(blank=True, db_column='Chat_API_Key', max_length=500, null=True)),
                ('directorate', models.CharField(blank=True, default='', max_length=150)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('school_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم المدرسة')),
                ('gemini_api_key', models.CharField(blank=True, db_column='Student_Gemini_API_Key', max_length=500, null=True)),
                ('daily_chat_limit', models.IntegerField(db_column='DailyChatLimit', default=20)),
                ('chats_today', models.IntegerField(db_column='ChatsToday', default=0)),
                ('last_chat_reset', models.DateField(db_column='LastChatReset', default=django.utils.timezone.now)),
                ('classid', models.ForeignKey(blank=True, db_column='ClassID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.class')),
                ('userid', models.OneToOneField(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Student',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Performancereport',
            fields=[
                ('reportid', models.AutoField(db_column='ReportID', primary_key=True, serialize=False)),
                ('avgattentionscore', models.FloatField(db_column='AvgAttentionScore')),
                ('testscore', models.IntegerField(db_column='TestScore')),
                ('totaltimespent', models.IntegerField(db_column='TotalTimeSpent')),
                ('teachercomments', models.TextField(blank=True, db_column='TeacherComments', null=True)),
                ('reportdate', models.DateTimeField(auto_now_add=True, db_column='ReportDate')),
                ('lessonid', models.ForeignKey(db_column='LessonID', on_delete=django.db.models.deletion.CASCADE, to='learning.lessoncontent')),
                ('studentid', models.ForeignKey(db_column='StudentID', on_delete=django.db.models.deletion.CASCADE, to='learning.student')),
            ],
            options={
                'db_table': 'PerformanceReport',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('parentid', models.AutoField(db_column='ParentID', primary_key=True, serialize=False)),
                ('gender', models.CharField(blank=True, choices=[('M', 'ذكر (والد)'), ('F', 'أنثى (والدة)')], db_column='Gender', default='', help_text='جنس ولي الأمر — يُستخدم للتحقق من نسب الطالب', max_length=1)),
                ('userid', models.OneToOneField(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('childid', models.ForeignKey(blank=True, db_column='ChildID', null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.student')),
            ],
            options={
                'db_table': 'Parent',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LessonWatchRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_records', to='learning.lessoncontent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_records', to='learning.student')),
            ],
        ),
        migrations.CreateModel(
            name='LearningStateSnapshot',
            fields=[
                ('snapshotid', models.AutoField(db_column='SnapshotID', primary_key=True, serialize=False)),
                ('current_attention_score', models.FloatField(db_column='CurrentAttentionScore', default=0.0, help_text='درجة الانتباه الحالية (0-100)')),
                ('current_learning_state', models.FloatField(db_column='CurrentLearningState', default=0.5, help_text='حالة التعلم الحالية (0-1)')),
                ('head_yaw', models.FloatField(blank=True, db_column='HeadYaw', help_text='زاوية التفات الرأس', null=True)),
                ('head_pitch', models.FloatField(blank=True, db_column='HeadPitch', help_text='زاوية النظر للأعلى/الأسفل', null=True)),
                ('head_roll', models.FloatField(blank=True, db_column='HeadRoll', help_text='زاوية الإمالة', null=True)),
                ('gaze_horizontal', models.FloatField(blank=True, db_column='GazeHorizontal', help_text='زاوية النظر الأفقية', null=True)),
                ('gaze_vertical', models.FloatField(blank=True, db_column='GazeVertical', help_text='زاوية النظر العمودية', null=True)),
                ('is_looking_away', models.BooleanField(db_column='IsLookingAway', default=False, help_text='هل ينظر بعيداً؟')),
                ('ear_value', models.FloatField(blank=True, db_column='EARValue', help_text='قيمة EAR', null=True)),
                ('is_drowsy', models.BooleanField(db_column='IsDrowsy', default=False, help_text='هل يظهر نعاس؟')),
                ('snapshot_time', models.DateTimeField(auto_now_add=True, db_column='SnapshotTime')),
                ('sessionid', models.ForeignKey(db_column='SessionID', on_delete=django.db.models.deletion.CASCADE, to='learning.learningsession')),
                ('studentid', models.ForeignKey(db_column='StudentID', on_delete=django.db.models.deletion.CASCADE, to='learning.student')),
            ],
            options={
                'db_table': 'LearningStateSnapshot',
                'ordering': ['-snapshot_time'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LearningState',
            fields=[
                ('stateid', models.AutoField(db_column='StateID', primary_key=True, serialize=False)),
                ('behavioral_engagement_score', models.FloatField(db_column='BehavioralEngagementScore', default=0.0, help_text='مؤشر الانخراط السلوكي (0-1) من تحليل حركة العين والرأس')),
                ('learning_state_probability', models.FloatField(db_column='LearningStateProbability', default=0.5, help_text='احتمالية حالة التعلم (0-1) - مؤشر شامل')),
                ('cognitive_connection_score', models.FloatField(db_column='CognitiveConnectionScore', default=0.5, help_text='مؤشر الاتصال المعرفي (0-1) من إجابات نقاط التحقق')),
                ('cognitive_load', models.CharField(choices=[('low', 'منخفض'), ('optimal', 'مثالي'), ('high', 'عالي'), ('overload', 'فائق')], db_column='CognitiveLoad', default='optimal', help_text='الحمل الإدراكي الحالي', max_length=20)),
                ('temporal_trend', models.CharField(choices=[('improving', 'محسّن'), ('stable', 'مستقر'), ('declining', 'تناقص'), ('fluctuating', 'متذبذب')], db_column='TemporalTrend', default='stable', help_text='الاتجاه الزمني لحالة التعلم', max_length=20)),
                ('time_window_start', models.DateTimeField(db_column='TimeWindowStart')),
                ('time_window_end', models.DateTimeField(db_column='TimeWindowEnd')),
                ('attention_samples_count', models.IntegerField(db_column='AttentionSamplesCount', default=0, help_text='عدد عينات الانتباه في هذه النافذة')),
                ('checkpoint_answers_count', models.IntegerField(db_column='CheckpointAnswersCount', default=0, help_text='عدد إجابات نقاط التحقق في هذه النافذة')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('sessionid', models.ForeignKey(db_column='SessionID', on_delete=django.db.models.deletion.CASCADE, to='learning.learningsession')),
                ('studentid', models.ForeignKey(db_column='StudentID', on_delete=django.db.models.deletion.CASCADE, to='learning.student')),
            ],
            options={
                'db_table': 'LearningState',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='learningsession',
            name='studentid',
            field=models.ForeignKey(db_column='StudentID', on_delete=django.db.models.deletion.CASCADE, to='learning.student'),
        ),
        migrations.CreateModel(
            name='StudentCheckpointAnswer',
            fields=[
                ('answerid', models.AutoField(db_column='AnswerID', primary_key=True, serialize=False)),
                ('selected_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], db_column='SelectedAnswer', help_text='الإجابة التي اختارها الطالب', max_length=10)),
                ('is_correct', models.BooleanField(db_column='IsCorrect', default=False, help_text='هل الإجابة صحيحة؟ (داخلي فقط - لا يُعرض للطالب)')),
                ('cognitive_connection_state', models.CharField(choices=[('strong', 'قوي - استمرارية الفهم'), ('weak', 'ضعيف مؤقت'), ('disconnected', 'منقطع')], db_column='CognitiveConnectionState', default='strong', help_text='حالة الاتصال المعرفي بناءً على الإجابة', max_length=20)),
                ('support_intervention_triggered', models.BooleanField(db_column='SupportInterventionTriggered', default=False, help_text='هل تم تفعيل الرجوع 5 ثواني لإعادة بناء السياق؟')),
                ('response_time', models.FloatField(blank=True, db_column='ResponseTime', help_text='المدة الزمنية التي احتاجها الطالب للاختيار (بالثواني)', null=True)),
                ('answered_at', models.DateTimeField(auto_now_add=True, db_column='AnsweredAt')),
                ('current_video_position', models.FloatField(blank=True, db_column='CurrentVideoPosition', help_text='موضع الفيديو الحالي بالثواني عند الإجابة', null=True)),
                ('current_paragraph_index', models.IntegerField(blank=True, db_column='CurrentParagraphIndex', help_text='رقم الفقرة الحالية عند الإجابة', null=True)),
                ('checkpoint', models.ForeignKey(db_column='CheckpointID', on_delete=django.db.models.deletion.CASCADE, to='learning.checkpoint')),
                ('sessionid', models.ForeignKey(blank=True, db_column='SessionID', null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.learningsession')),
                ('studentid', models.ForeignKey(db_column='StudentID', on_delete=django.db.models.deletion.CASCADE, to='learning.student')),
            ],
            options={
                'db_table': 'StudentCheckpointAnswer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subjectid', models.AutoField(db_column='SubjectID', primary_key=True, serialize=False)),
                ('subjectname', models.CharField(db_column='SubjectName', max_length=50)),
                ('classid', models.ForeignKey(blank=True, db_column='ClassID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.class')),
            ],
            options={
                'db_table': 'Subject',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='lessoncontent',
            name='subjectid',
            field=models.ForeignKey(db_column='SubjectID', on_delete=django.db.models.deletion.CASCADE, to='learning.subject'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacherid', models.AutoField(db_column='TeacherID', primary_key=True, serialize=False)),
                ('specialization', models.CharField(db_column='Specialization', max_length=100)),
                ('directorate', models.CharField(blank=True, db_column='Directorate', default='', max_length=100)),
                ('gemini_api_key', models.CharField(blank=True, db_column='Gemini_API_Key', max_length=500, null=True)),
                ('lessons_today', models.IntegerField(db_column='LessonsToday', default=0)),
                ('videos_today', models.IntegerField(db_column='VideosToday', default=0)),
                ('daily_lesson_limit', models.IntegerField(db_column='DailyLessonLimit', default=15)),
                ('daily_video_limit', models.IntegerField(db_column='DailyVideoLimit', default=2)),
                ('last_reset_date', models.DateField(db_column='LastResetDate', default=django.utils.timezone.now)),
                ('gemini_attempts_today', models.IntegerField(db_column='GeminiAttemptsToday', default=0)),
                ('daily_gemini_limit', models.IntegerField(db_column='DailyGeminiLimit', default=20)),
                ('gemini_last_reset_date', models.DateField(db_column='GeminiLastResetDate', default=django.utils.timezone.now)),
                ('assigned_classes', models.ManyToManyField(blank=True, related_name='teachers', to='learning.class')),
                ('userid', models.OneToOneField(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Teacher',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='teacherid',
            field=models.ForeignKey(db_column='TeacherID', on_delete=django.db.models.deletion.CASCADE, to='learning.teacher'),
        ),
        migrations.CreateModel(
            name='StudentTeacherAssignment',
            fields=[
                ('assignmentid', models.AutoField(db_column='AssignmentID', primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('classid', models.ForeignKey(blank=True, db_column='ClassID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.class')),
                ('studentid', models.ForeignKey(db_column='StudentID', on_delete=django.db.models.deletion.CASCADE, to='learning.student')),
                ('subjectid', models.ForeignKey(blank=True, db_column='SubjectID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.subject')),
                ('teacherid', models.ForeignKey(db_column='TeacherID', on_delete=django.db.models.deletion.CASCADE, to='learning.teacher')),
            ],
            options={
                'db_table': 'StudentTeacherAssignment',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='lessoncontent',
            name='teacherid',
            field=models.ForeignKey(db_column='TeacherID', on_delete=django.db.models.deletion.CASCADE, to='learning.teacher'),
        ),
        migrations.AddField(
            model_name='class',
            name='teacherid',
            field=models.ForeignKey(db_column='TeacherID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.teacher'),
        ),
        migrations.AddField(
            model_name='aiagent',
            name='teacherid',
            field=models.ForeignKey(blank=True, db_column='TeacherID', null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.teacher'),
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('testid', models.AutoField(db_column='TestID', primary_key=True, serialize=False)),
                ('testtitle', models.CharField(db_column='TestTitle', max_length=100)),
                ('totalquestions', models.IntegerField(db_column='TotalQuestions')),
                ('durationtaken', models.IntegerField(blank=True, db_column='DurationTaken', null=True)),
                ('test_version', models.IntegerField(db_column='TestVersion', default=1, help_text='نسخة الاختبار الحالية')),
                ('lessonid', models.ForeignKey(blank=True, db_column='LessonID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.lessoncontent')),
                ('subjectid', models.ForeignKey(blank=True, db_column='SubjectID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.subject')),
                ('teacherid', models.ForeignKey(db_column='TeacherID', on_delete=django.db.models.deletion.CASCADE, to='learning.teacher')),
            ],
            options={
                'db_table': 'Test',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('questionid', models.AutoField(db_column='QuestionID', primary_key=True, serialize=False)),
                ('questiontext', models.CharField(db_column='QuestionText', max_length=400)),
                ('optiona', models.CharField(db_column='OptionA', max_length=300)),
                ('optionb', models.CharField(db_column='OptionB', max_length=300)),
                ('optionc', models.CharField(blank=True, db_column='OptionC', max_length=300, null=True)),
                ('optiond', models.CharField(blank=True, db_column='OptionD', max_length=300, null=True)),
                ('correctanswer', models.CharField(db_column='CorrectAnswer', max_length=300)),
                ('points', models.IntegerField(db_column='Points')),
                ('testid', models.ForeignKey(db_column='TestID', on_delete=django.db.models.deletion.CASCADE, to='learning.test')),
            ],
            options={
                'db_table': 'Question',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Testattempt',
            fields=[
                ('attemptid', models.AutoField(db_column='AttemptID', primary_key=True, serialize=False)),
                ('first_attempt_score', models.IntegerField(blank=True, db_column='FirstAttemptScore', help_text='علامة المحاولة الأولى الحقيقية (للمعلم فقط)', null=True)),
                ('current_score', models.IntegerField(blank=True, db_column='CurrentScore', help_text='العلامة الحالية بعد جميع المحاولات', null=True)),
                ('total_attempts', models.IntegerField(db_column='TotalAttempts', default=1, help_text='عدد المحاولات الكلي')),
                ('teacherfeedback', models.TextField(blank=True, db_column='TeacherFeedback', null=True)),
                ('attemptdate', models.DateTimeField(auto_now_add=True, db_column='AttemptDate')),
                ('durationtaken', models.IntegerField(blank=True, db_column='DurationTaken', null=True)),
                ('test_version', models.IntegerField(db_column='TestVersion', default=1, help_text='نسخة الاختبار عند المحاولة')),
                ('progress_percentage', models.IntegerField(db_column='ProgressPercentage', default=0, help_text='نسبة التقدم للطالب (0-100)')),
                ('is_completed', models.BooleanField(db_column='IsCompleted', default=False, help_text='هل أكمل الطالب التقييم؟')),
                ('stars_earned', models.IntegerField(db_column='StarsEarned', default=0, help_text='عدد النجوم المكتسبة')),
                ('last_retry_date', models.DateTimeField(blank=True, db_column='LastRetryDate', help_text='تاريخ آخر محاولة إعادة', null=True)),
                ('studentid', models.ForeignKey(db_column='StudentID', on_delete=django.db.models.deletion.CASCADE, to='learning.student')),
                ('testid', models.ForeignKey(db_column='TestID', on_delete=django.db.models.deletion.CASCADE, to='learning.test')),
            ],
            options={
                'db_table': 'TestAttempt',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Studentanswer',
            fields=[
                ('answerid', models.AutoField(db_column='AnswerID', primary_key=True, serialize=False)),
                ('selectedoption', models.CharField(db_column='SelectedOption', max_length=50)),
                ('iscorrect', models.BooleanField(db_column='IsCorrect')),
                ('responsetimeseconds', models.IntegerField(blank=True, db_column='ResponseTimeSeconds', null=True)),
                ('attempt_number', models.IntegerField(db_column='AttemptNumber', default=1, help_text='رقم المحاولة لهذا السؤال')),
                ('needs_retry', models.BooleanField(db_column='NeedsRetry', default=False, help_text='هل يحتاج السؤال لإعادة المحاولة؟')),
                ('is_mastered', models.BooleanField(db_column='IsMastered', default=False, help_text='هل أتقن الطالب هذا السؤال؟')),
                ('questionid', models.ForeignKey(db_column='QuestionID', on_delete=django.db.models.deletion.CASCADE, to='learning.question')),
                ('attemptid', models.ForeignKey(db_column='AttemptID', on_delete=django.db.models.deletion.CASCADE, to='learning.testattempt')),
            ],
            options={
                'db_table': 'StudentAnswer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VRLesson',
            fields=[
                ('vr_id', models.AutoField(db_column='VR_ID', primary_key=True, serialize=False)),
                ('vr_url', models.URLField(blank=True, db_column='VR_URL', help_text='رابط منصة الواقع الافتراضي المصمم من قبل المعلم', max_length=1000, null=True)),
                ('design_platform_url', models.URLField(db_column='DesignPlatformURL', default='https://aistudio.google.com/apps/ea0032ea-b331-4cc8-a5fd-e59bbce58fbe?fullscreenApplet=true&showPreview=true&showAssistant=true', help_text='رابط منصة تصميم بيئة الواقع الافتراضي', max_length=1000)),
                ('vr_attachment', models.FileField(blank=True, db_column='VR_Attachment', help_text='مرفق إضافي للواقع الافتراضي (PDF, ZIP, أو أي ملف آخر)', null=True, upload_to='vr_attachments/')),
                ('is_published', models.BooleanField(db_column='IsPublished', default=False, help_text='هل تم نشر تجربة الواقع الافتراضي للطالب؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
                ('classroom', models.ForeignKey(blank=True, db_column='ClassID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.class')),
                ('lesson', models.OneToOneField(db_column='LessonID', on_delete=django.db.models.deletion.CASCADE, related_name='vr_experience', to='learning.lessoncontent')),
                ('subject', models.ForeignKey(blank=True, db_column='SubjectID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.subject')),
                ('teacher', models.ForeignKey(db_column='TeacherID', on_delete=django.db.models.deletion.CASCADE, to='learning.teacher')),
            ],
            options={
                'db_table': 'VRLesson',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StudentVRInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_downloaded_attachment', models.BooleanField(db_column='HasDownloadedAttachment', default=False, help_text='هل قام الطالب بتحميل المرفق؟')),
                ('has_explored_vr', models.BooleanField(db_column='HasExploredVR', default=False, help_text='هل قام الطالب بالضغط على زر استكشاف VR؟')),
                ('download_timestamp', models.DateTimeField(blank=True, db_column='DownloadTimestamp', help_text='وقت تحميل المرفق', null=True)),
                ('explore_timestamp', models.DateTimeField(blank=True, db_column='ExploreTimestamp', help_text='وقت استكشاف VR', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
                ('student', models.ForeignKey(db_column='StudentID', on_delete=django.db.models.deletion.CASCADE, related_name='vr_interactions', to='learning.student')),
                ('vr_lesson', models.ForeignKey(db_column='VRLessonID', on_delete=django.db.models.deletion.CASCADE, related_name='student_interactions', to='learning.vrlesson')),
            ],
            options={
                'db_table': 'StudentVRInteraction',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['userrole'], name='idx_user_role'),
        ),
        migrations.AddIndex(
            model_name='checkpoint',
            index=models.Index(fields=['lessonid'], name='idx_chk_lesson'),
        ),
        migrations.AddIndex(
            model_name='checkpoint',
            index=models.Index(fields=['lessonid', 'checkpoint_type'], name='idx_chk_lesson_type'),
        ),
        migrations.AddIndex(
            model_name='checkpoint',
            index=models.Index(fields=['video_timestamp'], name='idx_chk_timestamp'),
        ),
        migrations.AddIndex(
            model_name='performancereport',
            index=models.Index(fields=['studentid', '-reportdate'], name='idx_report_student_date'),
        ),
        migrations.AlterUniqueTogether(
            name='lessonwatchrecord',
            unique_together={('student', 'lesson')},
        ),
        migrations.AddIndex(
            model_name='learningstatesnapshot',
            index=models.Index(fields=['sessionid'], name='idx_lss_session'),
        ),
        migrations.AddIndex(
            model_name='learningstatesnapshot',
            index=models.Index(fields=['studentid'], name='idx_lss_student'),
        ),
        migrations.AddIndex(
            model_name='learningstatesnapshot',
            index=models.Index(fields=['snapshot_time'], name='idx_lss_time'),
        ),
        migrations.AddIndex(
            model_name='learningstatesnapshot',
            index=models.Index(fields=['sessionid', '-snapshot_time'], name='idx_lss_session_time'),
        ),
        migrations.AddIndex(
            model_name='learningstate',
            index=models.Index(fields=['sessionid'], name='idx_ls_session'),
        ),
        migrations.AddIndex(
            model_name='learningstate',
            index=models.Index(fields=['studentid'], name='idx_ls_student'),
        ),
        migrations.AddIndex(
            model_name='learningstate',
            index=models.Index(fields=['time_window_start'], name='idx_ls_time_start'),
        ),
        migrations.AddIndex(
            model_name='learningstate',
            index=models.Index(fields=['sessionid', '-created_at'], name='idx_ls_session_time'),
        ),
        migrations.AddIndex(
            model_name='studentcheckpointanswer',
            index=models.Index(fields=['studentid'], name='idx_stud_chk_ans'),
        ),
        migrations.AddIndex(
            model_name='studentcheckpointanswer',
            index=models.Index(fields=['checkpoint'], name='idx_chk_ans_chk'),
        ),
        migrations.AddIndex(
            model_name='studentcheckpointanswer',
            index=models.Index(fields=['sessionid'], name='idx_chk_ans_sess'),
        ),
        migrations.AddIndex(
            model_name='studentcheckpointanswer',
            index=models.Index(fields=['answered_at'], name='idx_chk_ans_time'),
        ),
        migrations.AlterUniqueTogether(
            name='studentteacherassignment',
            unique_together={('studentid', 'teacherid', 'subjectid')},
        ),
        migrations.AddIndex(
            model_name='lessoncontent',
            index=models.Index(fields=['teacherid', '-createdat'], name='idx_lesson_teacher_date'),
        ),
        migrations.AddIndex(
            model_name='lessoncontent',
            index=models.Index(fields=['subjectid'], name='idx_lesson_subjectid'),
        ),
        migrations.AddIndex(
            model_name='lessoncontent',
            index=models.Index(fields=['status'], name='idx_lesson_status'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['studentid', '-attemptdate'], name='idx_attempt_student_date'),
        ),
        migrations.AddIndex(
            model_name='studentanswer',
            index=models.Index(fields=['attemptid', 'questionid'], name='idx_answer_attempt_question'),
        ),
        migrations.AddIndex(
            model_name='vrlesson',
            index=models.Index(fields=['teacher'], name='idx_vr_teacher'),
        ),
        migrations.AddIndex(
            model_name='vrlesson',
            index=models.Index(fields=['classroom'], name='idx_vr_classroom'),
        ),
        migrations.AddIndex(
            model_name='vrlesson',
            index=models.Index(fields=['is_published'], name='idx_vr_published'),
        ),
        migrations.AddIndex(
            model_name='vrlesson',
            index=models.Index(fields=['lesson'], name='idx_vr_lesson'),
        ),
        migrations.AddIndex(
            model_name='studentvrinteraction',
            index=models.Index(fields=['vr_lesson', 'student'], name='idx_vr_interaction'),
        ),
        migrations.AddIndex(
            model_name='studentvrinteraction',
            index=models.Index(fields=['student'], name='idx_vr_student'),
        ),
        migrations.AlterUniqueTogether(
            name='studentvrinteraction',
            unique_together={('vr_lesson', 'student')},
        ),
    ]
